name: ts-coverage

on:
  pull_request:
    branches:
      - master
      - release/*
      - hotfix/*
      - major/*
      - chore/*
      - chore-*

jobs:
  validate:
    runs-on: ubuntu-latest
    name: 'Runner'

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/ts-coverage
        env:
          IGNORE: '[".github"]'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
